name: pull_request annotation

on:
  pull_request:

permissions: 
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo '::debug:: debug'
      - name: notice
        run: |
          echo ::notice:: notice
      - name: warning
        run: |
          echo ::warning:: warning
      - name: error
        run: |
          echo ::error:: error
      - name: status update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo '${{ toJSON(github.event.pull_request) }}'
          echo ${{ github.event.pull_request.head.sha }}
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/takesato/actions-inspection/statuses/${{ github.event.pull_request.head.sha }} \
            -f state='failure' \
            -f description='The build failure' \
            -f context='api test' 
      - name: state update
        run: |
          echo "changedState=false" >> $GITHUB_OUTPUT
          echo "stateMessage=use set-output state change" >> $GITHUB_OUTPUT