name: auto scale runner

on:
  workflow_dispatch:

permissions:
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  context:
    strategy:
      max-parallel: 4
      matrix:
        environment: [1, 2, 3, 4, 5, 6, 7, 8]
    runs-on: [self-hosted, linux]
    steps:
      - name: print environment
        run: echo '${{ matrix.environment }}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
