name: GitHub Script Sample

on:
  workflow_dispatch:
    inputs:
      push_branch:
        description: 'choose branch'
        required: true
permissions:
  contents: write

jobs:
  push_branch:
    runs-on: ubuntu-latest
    steps:
      - name: push branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.request('PATCH /repos/{owner}/{repo}/git/refs/heads/{ref}', {
              owner: 'takesato',
              repo: 'actions-inspection',
              ref: '${{ inputs.push_branch }}',
              sha: '${{ github.sha }}',
              force: true,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
