name: GitHub Script Sample

on:
  workflow_dispatch:
    inputs:
      push_branch:
        description: 'choose branch'
        required: true
      value:
        description: 'choice'
        type: choice
        options:
          - 
          - true
          - false
permissions: write-all
  # contents: write

jobs:
  push_branch:
    runs-on: ubuntu-latest
    steps:
      - name: push branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.request('PATCH /repos/{owner}/{repo}/git/refs/heads/{ref}', {
              owner: '${{ github.repository }}'.split('/')[0],
              repo: '${{ github.repository }}'.split('/')[1],
              ref: '${{ inputs.push_branch }}',
              sha: '${{ github.sha }}',
              force: true,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
      - name: update variables
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log('${{ inputs.value }}')
            await github.request('PATCH /repos/{owner}/{repo}/actions/variables/{name}', {
              owner: '${{ github.repository }}'.split('/')[0],
              repo: '${{ github.repository }}'.split('/')[1],
              name: 'SAMPLE_VAR1',
              value: '${{ inputs.push_branch }}',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            await github.request('PATCH /repositories/{repository_id}/environments/{environment_name}/variables/{name}', {
              repository_id: '${{ github.repository_id }}',
              name: 'SAMPLE_VAR1',
              environment_name: 'main',
              value: '${{ inputs.push_branch }}',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })