name: GitHub Script Sample

on:
  workflow_dispatch:
    inputs:
      push_branch:
        description: 'choose branch'
        required: true
permissions:
  contents: read
  id-token: write

jobs:
  push_branch:
    runs-on: ubuntu-latest
    steps:
      - name: push branch
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ inputs.push_branch }})
            console.log(${{ github.sha }})
            console.log(context.inputs);
            console.log(context.github);
            await github.request('PATCH /repos/{owner}/{repo}/git/refs/{ref}', {
              owner: 'takesato',
              repo: 'actions-inspection',
              ref: `origin/${{ inputs.push_branch }}`,
              sha: ${{ github.sha }},
              force: true,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
