name: pull_request context

on:
  pull_request:

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  WORKFLOW_VAR: Can you take over?
jobs:
  context:
    runs-on: ubuntu-latest
    # if: >-
    #   github.event_name == 'pull_request' ||
    #   github.event.state == 'error' ||
    #   github.event.state == 'failure'
    env:
      JOB_VAR: Can you take over?
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Set output
        run: echo "OUTPUT_VAR='Can you take over?'" >> $GITHUB_ENV
      - name: call composite action
        env:
          STEP_VAR: Can you take over?
        uses: ./.github/actions/variables/

